### ISSUE TITLE
'Incompatible cast' exception during serialize with Dydnamic types.[May be duplicated with Issue20]

### ISSUE THREAD

**Issue by inu4g0t** [c80k/capnproto-dotnetcore#29] opened 2019-12-09 05:32 UTC
I think the issue I found is duplicated with issue 20 where master branch has already fix the issue.

But the newest version I got from the unpack which is 1.1.112 still have issue.

Is there any version published which contains the fix?
===================

I wrote a simple type like:

`@0x99a09bebf96cb4a0;

struct SimpleValue {
	values @0: List(Int64);
}

struct Event(valueType) {
	key @0 : Text;
	value @1 : valueType;
}

struct SimpleEvent {
	event @0: Event(SimpleValue);
}`

And serialize it with:
`impleEvent ev = new SimpleEvent();

            // Generate inner value
            var v = new SimpleValue();

            var tmpValues = new List<long>();
            tmpValues.Add(1);
            v.Values = tmpValues;

            // Generate outer event

            ev.Event = new Event<SimpleValue>();
            ev.Event.Key = "K";

            ev.Event.Value = v;

            // Serialize
            var msg = MessageBuilder.Create();
            var root = msg.BuildRoot<SimpleEvent.WRITER>();
            ev.serialize(root);`

I got 

> An unhandled exception of type 'System.InvalidOperationException' occurred in Capnp.Net.Runtime.dll

during the last serialize.

I tested on both .NET core and .NET framework (4.6.2 and 4.7.2) with 
Capnp.Net.Runtime 1.1.112 and CapnpC.CSharp.MsBuild.Generation 1.1.112

=====
I also tried master but no such issues. Is there all ready a fix on this?

**Comment by c80k** [comment] 2019-12-09 19:36
Correct, this is a duplicate of issue #20. It was fixed with this commit:
https://github.com/c80k/capnproto-dotnetcore/commit/9a121245744390dce565adda3f8c9b594e3c13c1

**Comment by c80k** [comment] 2019-12-09 19:37
And no, there is no published version, yet.

**Comment by c80k** [comment] 2020-01-08 21:19
Update: Latest [release 1.2.138](https://github.com/c80k/capnproto-dotnetcore/releases/tag/v1.2.138) does contain the fix. The generator package was recently approved on Chocolatey.

**Closed** 2020-02-08 19:44 UTC
