### ISSUE TITLE
Codegen crashes with imports

### ISSUE THREAD

**Issue by KubaO** [c80k/capnproto-dotnetcore#7] opened 2019-08-23 14:23 UTC
I've run into several problems, most of them to do with apparent lack of support for imports:

- imported schemas are discarded in entirety,
- import namespaces are wrong,
- nested import types cause null dereference in the generator due to a null `TypeDefinition.Name`,
- type lookup follows all nested nodes, but should only follow all nodes below the generated file, since nodes under imported files are only provided by the frontend when necessary,
- enclosing typename clash resolution logic misses one level of types,
- identifiers that are C# keywords are not escaped,

I haven't had time to write testcases yet, but that's coming. I have a large proprietary schema (almost 10k nodes) that is a good testbed for those. I'll distill them over time.

For now, if anyone urgently needed a fix, feel free to peruse the branch below. It fixes all the problems I had, but I'm not sure that it's the best approach (not yet):

https://github.com/Bertec/capnproto-dotnetcore/tree/codegen-fixes-stable

- There's also a nasty "nail in the coffin problem", where generic types declared *after* their point of use in the schema file kill the codegen. This is perfectly valid in the schema, but requires two-pass model building, not unlike the upstream C++ codegen. This is a simple example that fails:

 ```
@0xab6541f552a22964;
interface Interface1  {
  method1 @0 () -> (arg : Interface2(AnyPointer));
}
interface Interface2(V) {}
```

I'll be keeping this issue updated with relevant "fix" commits until I get to having proper PR(s) with test cases.

**Comment by c80k** [comment] 2019-08-26 21:02
Thanks for reporting those issues. Your PR will be highly welcome. I just created a new experimental branch "codegen-dbg". It does not contain any fixes to the problems you mentioned, but adds some debugging convenience: Since it's usually `capnp` calling the generator, it requires some tweaks to get the debugger attached.

In this branch you will be able to do it the other way around: If you pass `<arguments>` to the generator (enter them on the VS debugging tab), it will by itself invoke `capnp compile -o<magictempfile> <arguments>`. This results in a binary file containing the code generator request. Afterwards, the generator processes this file.

This means that you may use the generator backend directly, without having to by the capnp frontend. You can stay within your debugging session.

The approach it quite hacky and intended for debugging purpose only. One more disclaimer: I did not test it extensively. I successfully reproduced your fail example (which requires only one .capnp file). In general, it's designed to pass also multiple arguments (several source, additional command line options like -I). But as said, I didn't try that yet.

**Comment by KubaO** [comment] 2019-08-26 21:17
I run it off binary repro cases :) capnp compile -Icanp\path -o-
testcase.capnp > testcase.canpnp.bin

**Comment by c80k** [comment] 2019-08-29 20:08
Cool, did't know about this switch!
I just merged your PR, made the CI happy again and put the new unit tests under CI execution, too. All tests passing. I also verified that the generator output is still the same with test.capnp (part of the original impl).

**Closed** 2019-08-30 19:23 UTC
